apiVersion: config.kio.kasten.io/v1alpha1
kind: BlueprintBinding
metadata:
  name: elasticsearch-eck-binding
  namespace: kasten-io
spec:
  blueprintRef:
    name: elasticsearch-eck-blueprint
    namespace: kasten-io
  resources:
    matchAll:
      - type:
          operator: In
          values:
            - group: elasticsearch.k8s.elastic.co
              resource: elasticsearches
      - annotations:
          key: kanister.kasten.io/blueprint
          operator: DoesNotExist
