apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-example
  namespace: couchbase-test
spec:
  image: couchbase/server:7.6.6
  security:
    adminSecret: cb-example-auth
  networking:
    exposeAdminConsole: false
  buckets:
    managed: true
  servers:
    - size: 1
      name: all-services
      services:
        - data
        - index
        - query
      volumeMounts:
        default: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: ebs-sc
        resources:
          requests:
            storage: 5Gi
