apiVersion: config.kio.kasten.io/v1alpha1
kind: BlueprintBinding
metadata:
  name: couchbase-operator-binding
  namespace: kasten-io
spec:
  blueprintRef:
    name: couchbase-operator-blueprint
    namespace: kasten-io
  resources:
    matchAll:
      - type:
          operator: In
          values:
            - group: couchbase.com
              resource: couchbaseclusters
      - annotations:
          key: kanister.kasten.io/blueprint
          operator: DoesNotExist
